### ISSUE TITLE
Code Example?

### ISSUE THREAD

**Issue by TobiasRipper** [rogerdahl/stm32-tm1637#3]
Im getting an error that is related to the syntax of the functions provided. Are there any code examples available to get the idea of how to use them properly?

https://snag.gy/PSjiQO.jpg
![image](https://user-images.githubusercontent.com/42154090/43739786-105cb8f6-997e-11e8-9a3c-96d07c7ea853.png)

**Comment by rogerdahl** [comment]
Did you remember to `#include "stm32_tm1637.h"`?
