### ISSUE TITLE
How to implement without leading zero?

### ISSUE THREAD

**Issue by digidhamu** [rogerdahl/stm32-tm1637#5]
Thanks for this elegant library.

How do I use this driver without leading zero e.g. `_ _ 1 2` rather than `0 0 1 2`?

**Comment by rogerdahl** [comment]
You'll have to modify the loop in `tm1637DisplayDecimal()`. Changing one line as below might do the trick. Untested. Let me know if it works for you:

```c

{
    unsigned char digitArr[4];
    for (int i = 0; i < 4; ++i) {
        digitArr[i] = v ? segmentMap[v % 10] : 0;    <-------
        if (i == 2 && displaySeparator) {
            digitArr[i] |= 1 << 7;
        }
        v /= 10;
    }
```

**Comment by digidhamu** [comment]
Perfectly working fine with this logic 👍
